version: '2'

services:
  web:
      image: nginx:latest
      ports:
          - "8000:80"
      volumes:
          - ./app:/app
          - ./conf/site.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
      - php
      networks:
      - simpletodo
  #    links:
  #        - php
  php:
      image: php:7.0-fpm
      volumes:
        - ./app:/app
        #- ./conf:/usr/local/etc/php/
      build:
        context: .
        dockerfile: php.dockerfile
      environment:
        XDEBUG_CONFIG: idekey=PHPSTORM
        #PHP_IDE_CONFIG: serverName=localhost
      ports:
       - "2222:22"
      networks:
      - simpletodo

  db:
    image: mysql:latest
# TODO: Save SQL db on PC
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: pass
    networks:
        - simpletodo


networks:
  simpletodo:
    driver: bridge
